## Preprocessing

In [94]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dla-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
# Drop the 'EIN' and 'NAME' columns
application_df = application_df.drop(['EIN', 'NAME'], axis=1)

In [96]:
# Display the updated DataFrame
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [97]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [98]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [99]:
# Assuming application_df is your DataFrame
# Replace values for 'Other 1'
application_df.loc[application_df['APPLICATION_TYPE'].isin(['T8', 'T7']), 'APPLICATION_TYPE'] = 'Other 1'

# Replace values for 'Other 2'
other_2_values = ['T10', 'T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']
application_df.loc[application_df['APPLICATION_TYPE'].isin(other_2_values), 'APPLICATION_TYPE'] = 'Other 2'

# Print the result
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3         27037
T4          1542
Other 1     1462
T6          1216
T5          1173
T19         1065
Other 2      804
Name: count, dtype: int64

In [100]:
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,Other 2,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [101]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
count = application_df['CLASSIFICATION'].value_counts()
count_1 = count[count > 1]
count_1

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [102]:
# Choose a cutoff value and create a list of classifications to be replaced
# Set the cutoff value
cutoff_value = 1000

# Create a list of classifications to be replaced
classifications_to_replace = application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() < cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls, "Other")
    
# Check to make sure binning was successful
print(application_df['CLASSIFICATION'].value_counts())

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [103]:
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,Other 2,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [104]:
# Convert categorical data to numeric with `pd.get_dummies`
# Convert categorical data to numeric with pd.get_dummies
application_df = pd.get_dummies(application_df)

# Convert boolean values to numeric (0 and 1)
application_df = application_df.astype(int)

# Display the resulting dataframe
print(application_df.head())

   STATUS  ASK_AMT  IS_SUCCESSFUL  APPLICATION_TYPE_Other 1  \
0       1     5000              1                         0
1       1   108590              1                         0
2       1     5000              0                         0
3       1     6692              1                         0
4       1   142590              1                         0

   APPLICATION_TYPE_Other 2  APPLICATION_TYPE_T19  APPLICATION_TYPE_T3  \
0                         1                     0                    0
1                         0                     0                    1
2                         0                     0                    0
3                         0                     0                    1
4                         0                     0                    1

   APPLICATION_TYPE_T4  APPLICATION_TYPE_T5  APPLICATION_TYPE_T6  ...  \
0                    0                    0                    0  ...
1                    0                    0                    0  ...
2                    0                    1                    0  ...
3                    0                    0                    0  ...
4                    0                    0                    0  ...

   INCOME_AMT_1-9999  INCOME_AMT_10000-24999  INCOME_AMT_100000-499999  \
0                  0                       0                         0
1                  1                       0                         0
2                  0                       0                         0
3                  0                       1                         0
4                  0                       0                         1

   INCOME_AMT_10M-50M  INCOME_AMT_1M-5M  INCOME_AMT_25000-99999  \
0                   0                 0                       0
1                   0                 0                       0
2                   0                 0                       0
3                   0                 0                       0
4                   0                 0                       0

   INCOME_AMT_50M+  INCOME_AMT_5M-10M  SPECIAL_CONSIDERATIONS_N  \
0                0                  0                         1
1                0                  0                         1
2                0                  0                         1
3                0                  0                         1
4                0                  0                         1

   SPECIAL_CONSIDERATIONS_Y
0                         0
1                         0
2                         0
3                         0
4                         0

[5 rows x 42 columns]

In [85]:
# Split our preprocessed data into our features and target arrays
y = application_df.IS_SUCCESSFUL.values
X = application_df.drop(columns=["IS_SUCCESSFUL"]).values

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [86]:
y

array([1, 1, 0, ..., 0, 1, 0])

In [87]:
X

array([[       1,     5000,        0, ...,        0,        1,        0],
       [       1,   108590,        0, ...,        0,        1,        0],
       [       1,     5000,        0, ...,        0,        1,        0],
       ...,
       [       1,     5000,        0, ...,        0,        1,        0],
       [       1,     5000,        0, ...,        0,        1,        0],
       [       1, 36500179,        0, ...,        0,        1,        0]])

In [88]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [89]:
X_train_scaled

array([[ 0.01079982, -0.04167889, -0.20842982, ..., -0.07450354,
         0.02925687, -0.02925687],
       [ 0.01079982, -0.04191145, -0.20842982, ..., -0.07450354,
         0.02925687, -0.02925687],
       [ 0.01079982, -0.04161838, -0.20842982, ..., -0.07450354,
         0.02925687, -0.02925687],
       ...,
       [ 0.01079982, -0.03942355, -0.20842982, ..., -0.07450354,
         0.02925687, -0.02925687],
       [ 0.01079982, -0.04191145, -0.20842982, ..., -0.07450354,
         0.02925687, -0.02925687],
       [ 0.01079982, -0.04191145, -0.20842982, ..., -0.07450354,
         0.02925687, -0.02925687]])

## Compile, Train and Evaluate the Model

In [90]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn_model = tf.keras.models.Sequential()
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu", input_dim=41))
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu"))
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_43 (Dense)            (None, 16)                672

 dense_44 (Dense)            (None, 16)                272

 dense_45 (Dense)            (None, 1)                 17

=================================================================
Total params: 961 (3.75 KB)
Trainable params: 961 (3.75 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [91]:
# Compile the model - Run 50 epochs
# Compile the Sequential model together and customise metrics
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

fit_model = nn_model.fit(X_train_scaled, y_train, epochs=50)
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/50
804/804 [==============================] - 2s 901us/step - loss: 0.5961 - accuracy: 0.6963
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5569 - accuracy: 0.7285
Epoch 3/50
804/804 [==============================] - 1s 970us/step - loss: 0.5537 - accuracy: 0.7293
Epoch 4/50
804/804 [==============================] - 1s 901us/step - loss: 0.5519 - accuracy: 0.7295
Epoch 5/50
804/804 [==============================] - 1s 914us/step - loss: 0.5504 - accuracy: 0.7321
Epoch 6/50
804/804 [==============================] - 1s 932us/step - loss: 0.5494 - accuracy: 0.7321
Epoch 7/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7325
Epoch 8/50
804/804 [==============================] - 1s 929us/step - loss: 0.5477 - accuracy: 0.7329
Epoch 9/50
804/804 [==============================] - 1s 902us/step - loss: 0.5473 - accuracy: 0.7341
Epoch 10/50
804/804 [==============================] - 1s 879us/step - loss: 0.5470 - accuracy: 0.7337
Epoch 11/50
804/804 [==============================] - 1s 894us/step - loss: 0.5460 - accuracy: 0.7343
Epoch 12/50
804/804 [==============================] - 1s 886us/step - loss: 0.5459 - accuracy: 0.7356
Epoch 13/50
804/804 [==============================] - 1s 962us/step - loss: 0.5458 - accuracy: 0.7343
Epoch 14/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5453 - accuracy: 0.7348
Epoch 15/50
804/804 [==============================] - 1s 916us/step - loss: 0.5453 - accuracy: 0.7350
Epoch 16/50
804/804 [==============================] - 1s 892us/step - loss: 0.5449 - accuracy: 0.7361
Epoch 17/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5448 - accuracy: 0.7347
Epoch 18/50
804/804 [==============================] - 1s 876us/step - loss: 0.5448 - accuracy: 0.7354
Epoch 19/50
804/804 [==============================] - 1s 878us/step - loss: 0.5443 - accuracy: 0.7350
Epoch 20/50
804/804 [==============================] - 1s 921us/step - loss: 0.5441 - accuracy: 0.7365
Epoch 21/50
804/804 [==============================] - 1s 886us/step - loss: 0.5442 - accuracy: 0.7370
Epoch 22/50
804/804 [==============================] - 1s 903us/step - loss: 0.5439 - accuracy: 0.7367
Epoch 23/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7370
Epoch 24/50
804/804 [==============================] - 1s 983us/step - loss: 0.5434 - accuracy: 0.7372
Epoch 25/50
804/804 [==============================] - 1s 966us/step - loss: 0.5429 - accuracy: 0.7372
Epoch 26/50
804/804 [==============================] - 1s 887us/step - loss: 0.5434 - accuracy: 0.7367
Epoch 27/50
804/804 [==============================] - 1s 907us/step - loss: 0.5429 - accuracy: 0.7368
Epoch 28/50
804/804 [==============================] - 1s 917us/step - loss: 0.5430 - accuracy: 0.7373
Epoch 29/50
804/804 [==============================] - 1s 907us/step - loss: 0.5430 - accuracy: 0.7365
Epoch 30/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7370
Epoch 31/50
804/804 [==============================] - 1s 868us/step - loss: 0.5423 - accuracy: 0.7374
Epoch 32/50
804/804 [==============================] - 1s 886us/step - loss: 0.5424 - accuracy: 0.7363
Epoch 33/50
804/804 [==============================] - 1s 879us/step - loss: 0.5424 - accuracy: 0.7377
Epoch 34/50
804/804 [==============================] - 1s 884us/step - loss: 0.5419 - accuracy: 0.7378
Epoch 35/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7375
Epoch 36/50
804/804 [==============================] - 1s 921us/step - loss: 0.5421 - accuracy: 0.7378
Epoch 37/50
804/804 [==============================] - 1s 882us/step - loss: 0.5417 - accuracy: 0.7381
Epoch 38/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7373
Epoch 39/50
804/804 [==============================] - 1s 877us/step - loss: 0.5416 - accuracy: 0.7374
Epoch 40/50
804/804 [==============================] - 1s 940us/step - loss: 0.5413 - accuracy: 0.7374
Epoch 41/50
804/804 [==============================] - 1s 952us/step - loss: 0.5411 - accuracy: 0.7384
Epoch 42/50
804/804 [==============================] - 1s 988us/step - loss: 0.5413 - accuracy: 0.7376
Epoch 43/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7378
Epoch 44/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5411 - accuracy: 0.7384
Epoch 45/50
804/804 [==============================] - 1s 883us/step - loss: 0.5411 - accuracy: 0.7389
Epoch 46/50
804/804 [==============================] - 1s 889us/step - loss: 0.5413 - accuracy: 0.7384
Epoch 47/50
804/804 [==============================] - 1s 890us/step - loss: 0.5410 - accuracy: 0.7378
Epoch 48/50
804/804 [==============================] - 1s 902us/step - loss: 0.5407 - accuracy: 0.7380
Epoch 49/50
804/804 [==============================] - 1s 902us/step - loss: 0.5402 - accuracy: 0.7381
Epoch 50/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5408 - accuracy: 0.7382
268/268 - 0s - loss: 0.5582 - accuracy: 0.7242 - 265ms/epoch - 987us/step
Loss: 0.5581744313240051, Accuracy: 0.7241982221603394

In [107]:
# Compile the model - Run 100 epochs
# Compile the Sequential model together and customise metrics
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/100
804/804 [==============================] - 1s 969us/step - loss: 0.5409 - accuracy: 0.7383
Epoch 2/100
804/804 [==============================] - 1s 858us/step - loss: 0.5408 - accuracy: 0.7385
Epoch 3/100
804/804 [==============================] - 1s 908us/step - loss: 0.5407 - accuracy: 0.7383
Epoch 4/100
804/804 [==============================] - 1s 884us/step - loss: 0.5405 - accuracy: 0.7393
Epoch 5/100
804/804 [==============================] - 1s 864us/step - loss: 0.5404 - accuracy: 0.7385
Epoch 6/100
804/804 [==============================] - 1s 919us/step - loss: 0.5403 - accuracy: 0.7384
Epoch 7/100
804/804 [==============================] - 1s 977us/step - loss: 0.5406 - accuracy: 0.7393
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7380
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5407 - accuracy: 0.7382
Epoch 10/100
804/804 [==============================] - 1s 884us/step - loss: 0.5395 - accuracy: 0.7390
Epoch 11/100
804/804 [==============================] - 1s 935us/step - loss: 0.5399 - accuracy: 0.7381
Epoch 12/100
804/804 [==============================] - 1s 878us/step - loss: 0.5403 - accuracy: 0.7387
Epoch 13/100
804/804 [==============================] - 1s 864us/step - loss: 0.5399 - accuracy: 0.7395
Epoch 14/100
804/804 [==============================] - 1s 876us/step - loss: 0.5400 - accuracy: 0.7390
Epoch 15/100
804/804 [==============================] - 1s 968us/step - loss: 0.5397 - accuracy: 0.7385
Epoch 16/100
804/804 [==============================] - 1s 974us/step - loss: 0.5400 - accuracy: 0.7394
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5395 - accuracy: 0.7397
Epoch 18/100
804/804 [==============================] - 1s 887us/step - loss: 0.5394 - accuracy: 0.7394
Epoch 19/100
804/804 [==============================] - 1s 884us/step - loss: 0.5398 - accuracy: 0.7390
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5398 - accuracy: 0.7394
Epoch 21/100
804/804 [==============================] - 1s 898us/step - loss: 0.5395 - accuracy: 0.7394
Epoch 22/100
804/804 [==============================] - 1s 934us/step - loss: 0.5395 - accuracy: 0.7386
Epoch 23/100
804/804 [==============================] - 1s 859us/step - loss: 0.5392 - accuracy: 0.7389
Epoch 24/100
804/804 [==============================] - 1s 870us/step - loss: 0.5395 - accuracy: 0.7393
Epoch 25/100
804/804 [==============================] - 1s 897us/step - loss: 0.5393 - accuracy: 0.7394
Epoch 26/100
804/804 [==============================] - 1s 872us/step - loss: 0.5393 - accuracy: 0.7393
Epoch 27/100
804/804 [==============================] - 1s 985us/step - loss: 0.5394 - accuracy: 0.7396
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7386
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5393 - accuracy: 0.7385
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7397
Epoch 31/100
804/804 [==============================] - 1s 968us/step - loss: 0.5394 - accuracy: 0.7400
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7387
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7390
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7398
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7393
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5386 - accuracy: 0.7390
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7393
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5388 - accuracy: 0.7386
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7392
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5389 - accuracy: 0.7391
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7379
Epoch 42/100
804/804 [==============================] - 1s 922us/step - loss: 0.5387 - accuracy: 0.7399
Epoch 43/100
804/804 [==============================] - 1s 877us/step - loss: 0.5387 - accuracy: 0.7401
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5389 - accuracy: 0.7400
Epoch 45/100
804/804 [==============================] - 1s 913us/step - loss: 0.5387 - accuracy: 0.7401
Epoch 46/100
804/804 [==============================] - 1s 876us/step - loss: 0.5387 - accuracy: 0.7400
Epoch 47/100
804/804 [==============================] - 1s 933us/step - loss: 0.5386 - accuracy: 0.7391
Epoch 48/100
804/804 [==============================] - 1s 889us/step - loss: 0.5385 - accuracy: 0.7395
Epoch 49/100
804/804 [==============================] - 1s 899us/step - loss: 0.5385 - accuracy: 0.7397
Epoch 50/100
804/804 [==============================] - 1s 878us/step - loss: 0.5386 - accuracy: 0.7393
Epoch 51/100
804/804 [==============================] - 1s 917us/step - loss: 0.5384 - accuracy: 0.7397
Epoch 52/100
804/804 [==============================] - 1s 873us/step - loss: 0.5384 - accuracy: 0.7390
Epoch 53/100
804/804 [==============================] - 1s 864us/step - loss: 0.5388 - accuracy: 0.7399
Epoch 54/100
804/804 [==============================] - 1s 893us/step - loss: 0.5383 - accuracy: 0.7402
Epoch 55/100
804/804 [==============================] - 1s 913us/step - loss: 0.5386 - accuracy: 0.7400
Epoch 56/100
804/804 [==============================] - 1s 974us/step - loss: 0.5384 - accuracy: 0.7396
Epoch 57/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5383 - accuracy: 0.7402
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5383 - accuracy: 0.7401
Epoch 59/100
804/804 [==============================] - 1s 895us/step - loss: 0.5382 - accuracy: 0.7408
Epoch 60/100
804/804 [==============================] - 1s 924us/step - loss: 0.5385 - accuracy: 0.7402
Epoch 61/100
804/804 [==============================] - 1s 954us/step - loss: 0.5383 - accuracy: 0.7399
Epoch 62/100
804/804 [==============================] - 1s 868us/step - loss: 0.5382 - accuracy: 0.7388
Epoch 63/100
804/804 [==============================] - 1s 907us/step - loss: 0.5381 - accuracy: 0.7399
Epoch 64/100
804/804 [==============================] - 1s 1000us/step - loss: 0.5385 - accuracy: 0.7392
Epoch 65/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7397
Epoch 66/100
804/804 [==============================] - 1s 962us/step - loss: 0.5381 - accuracy: 0.7397
Epoch 67/100
804/804 [==============================] - 1s 933us/step - loss: 0.5378 - accuracy: 0.7406
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5381 - accuracy: 0.7410
Epoch 69/100
804/804 [==============================] - 1s 945us/step - loss: 0.5380 - accuracy: 0.7404
Epoch 70/100
804/804 [==============================] - 1s 944us/step - loss: 0.5379 - accuracy: 0.7400
Epoch 71/100
804/804 [==============================] - 1s 984us/step - loss: 0.5378 - accuracy: 0.7406
Epoch 72/100
804/804 [==============================] - 1s 899us/step - loss: 0.5379 - accuracy: 0.7394
Epoch 73/100
804/804 [==============================] - 1s 941us/step - loss: 0.5380 - accuracy: 0.7404
Epoch 74/100
804/804 [==============================] - 1s 872us/step - loss: 0.5376 - accuracy: 0.7390
Epoch 75/100
804/804 [==============================] - 1s 894us/step - loss: 0.5383 - accuracy: 0.7400
Epoch 76/100
804/804 [==============================] - 1s 889us/step - loss: 0.5381 - accuracy: 0.7399
Epoch 77/100
804/804 [==============================] - 1s 864us/step - loss: 0.5375 - accuracy: 0.7404
Epoch 78/100
804/804 [==============================] - 1s 856us/step - loss: 0.5377 - accuracy: 0.7401
Epoch 79/100
804/804 [==============================] - 1s 889us/step - loss: 0.5378 - accuracy: 0.7403
Epoch 80/100

804/804 [==============================] - 1s 875us/step - loss: 0.5379 - accuracy: 0.7399
Epoch 81/100
804/804 [==============================] - 1s 887us/step - loss: 0.5376 - accuracy: 0.7398
Epoch 82/100
804/804 [==============================] - 1s 870us/step - loss: 0.5375 - accuracy: 0.7405
Epoch 83/100
804/804 [==============================] - 1s 854us/step - loss: 0.5380 - accuracy: 0.7401
Epoch 84/100
804/804 [==============================] - 1s 866us/step - loss: 0.5380 - accuracy: 0.7399
Epoch 85/100
804/804 [==============================] - 1s 868us/step - loss: 0.5375 - accuracy: 0.7408
Epoch 86/100
804/804 [==============================] - 1s 857us/step - loss: 0.5378 - accuracy: 0.7406
Epoch 87/100
804/804 [==============================] - 1s 853us/step - loss: 0.5378 - accuracy: 0.7409
Epoch 88/100
804/804 [==============================] - 1s 876us/step - loss: 0.5375 - accuracy: 0.7404
Epoch 89/100
804/804 [==============================] - 1s 889us/step - loss: 0.5375 - accuracy: 0.7410
Epoch 90/100
804/804 [==============================] - 1s 847us/step - loss: 0.5376 - accuracy: 0.7408
Epoch 91/100
804/804 [==============================] - 1s 849us/step - loss: 0.5377 - accuracy: 0.7406
Epoch 92/100
804/804 [==============================] - 1s 880us/step - loss: 0.5375 - accuracy: 0.7404
Epoch 93/100
804/804 [==============================] - 1s 847us/step - loss: 0.5373 - accuracy: 0.7406
Epoch 94/100
804/804 [==============================] - 1s 852us/step - loss: 0.5375 - accuracy: 0.7406
Epoch 95/100
804/804 [==============================] - 1s 848us/step - loss: 0.5374 - accuracy: 0.7402
Epoch 96/100
804/804 [==============================] - 1s 880us/step - loss: 0.5374 - accuracy: 0.7417
Epoch 97/100
804/804 [==============================] - 1s 857us/step - loss: 0.5378 - accuracy: 0.7403
Epoch 98/100
804/804 [==============================] - 1s 873us/step - loss: 0.5374 - accuracy: 0.7402
Epoch 99/100
804/804 [==============================] - 1s 899us/step - loss: 0.5376 - accuracy: 0.7401
Epoch 100/100
804/804 [==============================] - 1s 969us/step - loss: 0.5373 - accuracy: 0.7393
268/268 - 0s - loss: 0.5593 - accuracy: 0.7251 - 270ms/epoch - 1ms/step
Loss: 0.5593131184577942, Accuracy: 0.7251312136650085

In [92]:
nn_model.save("AlphabetSoupCharity.h5")

C:\Users\patricia.deassis\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [93]:
nn_model.save("AlphabetSoupCharity.keras")

# OPTION 2 - OPTIMIZATION
### DROP 4 ADDITIONAL COLUMNS , RUN 25 AND RUN 100 AND 150 EPOCHS

In [108]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dla-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [109]:
# Drop the 'EIN' and 'NAME' columns
application_df = application_df.drop(['EIN', 'NAME'], axis=1)

In [110]:
application_df.loc[application_df['APPLICATION_TYPE'].isin(['T8', 'T7']), 'APPLICATION_TYPE'] = 'Other 1'

# Replace values for 'Other 2'
other_2_values = ['T10', 'T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']
application_df.loc[application_df['APPLICATION_TYPE'].isin(other_2_values), 'APPLICATION_TYPE'] = 'Other 2'

# Print the result
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3         27037
T4          1542
Other 1     1462
T6          1216
T5          1173
T19         1065
Other 2      804
Name: count, dtype: int64

In [111]:
# Choose a cutoff value and create a list of classifications to be replaced
# Set the cutoff value
cutoff_value = 1000

# Create a list of classifications to be replaced
classifications_to_replace = application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() < cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls, "Other")
    
# Check to make sure binning was successful
print(application_df['CLASSIFICATION'].value_counts())

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [112]:
# Convert categorical data to numeric with pd.get_dummies
application_df = pd.get_dummies(application_df)

# Convert boolean values to numeric (0 and 1)
application_df = application_df.astype(int)

# Display the resulting dataframe
print(application_df.head())

   STATUS  ASK_AMT  IS_SUCCESSFUL  APPLICATION_TYPE_Other 1  \
0       1     5000              1                         0
1       1   108590              1                         0
2       1     5000              0                         0
3       1     6692              1                         0
4       1   142590              1                         0

   APPLICATION_TYPE_Other 2  APPLICATION_TYPE_T19  APPLICATION_TYPE_T3  \
0                         1                     0                    0
1                         0                     0                    1
2                         0                     0                    0
3                         0                     0                    1
4                         0                     0                    1

   APPLICATION_TYPE_T4  APPLICATION_TYPE_T5  APPLICATION_TYPE_T6  ...  \
0                    0                    0                    0  ...
1                    0                    0                    0  ...
2                    0                    1                    0  ...
3                    0                    0                    0  ...
4                    0                    0                    0  ...

   INCOME_AMT_1-9999  INCOME_AMT_10000-24999  INCOME_AMT_100000-499999  \
0                  0                       0                         0
1                  1                       0                         0
2                  0                       0                         0
3                  0                       1                         0
4                  0                       0                         1

   INCOME_AMT_10M-50M  INCOME_AMT_1M-5M  INCOME_AMT_25000-99999  \
0                   0                 0                       0
1                   0                 0                       0
2                   0                 0                       0
3                   0                 0                       0
4                   0                 0                       0

   INCOME_AMT_50M+  INCOME_AMT_5M-10M  SPECIAL_CONSIDERATIONS_N  \
0                0                  0                         1
1                0                  0                         1
2                0                  0                         1
3                0                  0                         1
4                0                  0                         1

   SPECIAL_CONSIDERATIONS_Y
0                         0
1                         0
2                         0
3                         0
4                         0

[5 rows x 42 columns]

In [113]:
# Split our preprocessed data into our features and target arrays
y = application_df.IS_SUCCESSFUL.values
X = application_df.drop(columns=["IS_SUCCESSFUL", "STATUS", "SPECIAL_CONSIDERATIONS_N", "SPECIAL_CONSIDERATIONS_Y","ASK_AMT"]).values

# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [114]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [115]:
X_train_scaled

array([[-0.20842982, -0.15558816, -0.17915797, ...,  2.86649057,
        -0.06340457, -0.07450354],
       [-0.20842982, -0.15558816, -0.17915797, ..., -0.34885864,
        -0.06340457, -0.07450354],
       [-0.20842982, -0.15558816, -0.17915797, ..., -0.34885864,
        -0.06340457, -0.07450354],
       ...,
       [-0.20842982, -0.15558816, -0.17915797, ..., -0.34885864,
        -0.06340457, -0.07450354],
       [-0.20842982, -0.15558816, -0.17915797, ..., -0.34885864,
        -0.06340457, -0.07450354],
       [-0.20842982, -0.15558816, -0.17915797, ..., -0.34885864,
        -0.06340457, -0.07450354]])

In [116]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn_model = tf.keras.models.Sequential()
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu", input_dim=37))
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu"))
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential_16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_46 (Dense)            (None, 16)                608

 dense_47 (Dense)            (None, 16)                272

 dense_48 (Dense)            (None, 1)                 17

=================================================================
Total params: 897 (3.50 KB)
Trainable params: 897 (3.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [117]:
# Train the model - testing drop 2 more columns and run 25 epochs
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

fit_model = nn_model.fit(X_train_scaled, y_train, epochs=25)
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/25
804/804 [==============================] - 1s 887us/step - loss: 0.5889 - accuracy: 0.7075
Epoch 2/25
804/804 [==============================] - 1s 876us/step - loss: 0.5586 - accuracy: 0.7296
Epoch 3/25
804/804 [==============================] - 1s 916us/step - loss: 0.5545 - accuracy: 0.7327
Epoch 4/25
804/804 [==============================] - 1s 907us/step - loss: 0.5524 - accuracy: 0.7325
Epoch 5/25
804/804 [==============================] - 1s 1ms/step - loss: 0.5511 - accuracy: 0.7335
Epoch 6/25
804/804 [==============================] - 1s 901us/step - loss: 0.5505 - accuracy: 0.7332
Epoch 7/25
804/804 [==============================] - 1s 884us/step - loss: 0.5493 - accuracy: 0.7324
Epoch 8/25
804/804 [==============================] - 1s 912us/step - loss: 0.5491 - accuracy: 0.7332
Epoch 9/25
804/804 [==============================] - 1s 892us/step - loss: 0.5485 - accuracy: 0.7338
Epoch 10/25
804/804 [==============================] - 1s 887us/step - loss: 0.5482 - accuracy: 0.7331
Epoch 11/25
804/804 [==============================] - 1s 877us/step - loss: 0.5477 - accuracy: 0.7336
Epoch 12/25
804/804 [==============================] - 1s 885us/step - loss: 0.5471 - accuracy: 0.7346
Epoch 13/25
804/804 [==============================] - 1s 907us/step - loss: 0.5470 - accuracy: 0.7338
Epoch 14/25
804/804 [==============================] - 1s 892us/step - loss: 0.5469 - accuracy: 0.7344
Epoch 15/25
804/804 [==============================] - 1s 875us/step - loss: 0.5463 - accuracy: 0.7343
Epoch 16/25
804/804 [==============================] - 1s 910us/step - loss: 0.5462 - accuracy: 0.7357
Epoch 17/25
804/804 [==============================] - 1s 1ms/step - loss: 0.5459 - accuracy: 0.7347
Epoch 18/25
804/804 [==============================] - 1s 929us/step - loss: 0.5457 - accuracy: 0.7349
Epoch 19/25
804/804 [==============================] - 1s 896us/step - loss: 0.5459 - accuracy: 0.7353
Epoch 20/25
804/804 [==============================] - 1s 958us/step - loss: 0.5453 - accuracy: 0.7357
Epoch 21/25
804/804 [==============================] - 1s 909us/step - loss: 0.5452 - accuracy: 0.7354
Epoch 22/25
804/804 [==============================] - 1s 898us/step - loss: 0.5449 - accuracy: 0.7348
Epoch 23/25
804/804 [==============================] - 1s 913us/step - loss: 0.5448 - accuracy: 0.7359
Epoch 24/25
804/804 [==============================] - 1s 987us/step - loss: 0.5443 - accuracy: 0.7341
Epoch 25/25
804/804 [==============================] - 1s 909us/step - loss: 0.5444 - accuracy: 0.7360
268/268 - 0s - loss: 0.5595 - accuracy: 0.7229 - 257ms/epoch - 959us/step
Loss: 0.5594766736030579, Accuracy: 0.7229154706001282

In [118]:
# Train the model - testing drop 2 more columns and run 100 epochs
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7350
Epoch 2/100
804/804 [==============================] - 1s 921us/step - loss: 0.5438 - accuracy: 0.7358
Epoch 3/100
804/804 [==============================] - 1s 862us/step - loss: 0.5438 - accuracy: 0.7362
Epoch 4/100
804/804 [==============================] - 1s 902us/step - loss: 0.5435 - accuracy: 0.7360
Epoch 5/100
804/804 [==============================] - 1s 883us/step - loss: 0.5439 - accuracy: 0.7359
Epoch 6/100
804/804 [==============================] - 1s 975us/step - loss: 0.5434 - accuracy: 0.7366
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7359
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7364
Epoch 9/100
804/804 [==============================] - 1s 924us/step - loss: 0.5431 - accuracy: 0.7352
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7362
Epoch 11/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7369
Epoch 12/100
804/804 [==============================] - 1s 919us/step - loss: 0.5424 - accuracy: 0.7378
Epoch 13/100
804/804 [==============================] - 1s 876us/step - loss: 0.5425 - accuracy: 0.7370
Epoch 14/100
804/804 [==============================] - 1s 887us/step - loss: 0.5429 - accuracy: 0.7364
Epoch 15/100
804/804 [==============================] - 1s 914us/step - loss: 0.5427 - accuracy: 0.7362
Epoch 16/100
804/804 [==============================] - 1s 920us/step - loss: 0.5424 - accuracy: 0.7370
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7367
Epoch 18/100
804/804 [==============================] - 1s 974us/step - loss: 0.5423 - accuracy: 0.7370
Epoch 19/100
804/804 [==============================] - 1s 875us/step - loss: 0.5422 - accuracy: 0.7361
Epoch 20/100
804/804 [==============================] - 1s 893us/step - loss: 0.5419 - accuracy: 0.7372
Epoch 21/100
804/804 [==============================] - 1s 888us/step - loss: 0.5423 - accuracy: 0.7367
Epoch 22/100
804/804 [==============================] - 1s 870us/step - loss: 0.5416 - accuracy: 0.7371
Epoch 23/100
804/804 [==============================] - 1s 927us/step - loss: 0.5417 - accuracy: 0.7360
Epoch 24/100
804/804 [==============================] - 1s 900us/step - loss: 0.5418 - accuracy: 0.7383
Epoch 25/100
804/804 [==============================] - 1s 873us/step - loss: 0.5418 - accuracy: 0.7371
Epoch 26/100
804/804 [==============================] - 1s 868us/step - loss: 0.5415 - accuracy: 0.7375
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7377
Epoch 28/100
804/804 [==============================] - 1s 871us/step - loss: 0.5414 - accuracy: 0.7374
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7375
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5408 - accuracy: 0.7372
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7379
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5411 - accuracy: 0.7378
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7382
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5413 - accuracy: 0.7381
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7378
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7386
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5407 - accuracy: 0.7383
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5408 - accuracy: 0.7387
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5407 - accuracy: 0.7384
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7386
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5404 - accuracy: 0.7391
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accuracy: 0.7380
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7383
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5408 - accuracy: 0.7374
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5401 - accuracy: 0.7375
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5401 - accuracy: 0.7381
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5403 - accuracy: 0.7382
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7382
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5401 - accuracy: 0.7387
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5404 - accuracy: 0.7385
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5403 - accuracy: 0.7393
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7385
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5400 - accuracy: 0.7385
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5400 - accuracy: 0.7386
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7385
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5398 - accuracy: 0.7399
Epoch 57/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5398 - accuracy: 0.7385
Epoch 58/100
804/804 [==============================] - 1s 906us/step - loss: 0.5399 - accuracy: 0.7384
Epoch 59/100
804/804 [==============================] - 1s 934us/step - loss: 0.5398 - accuracy: 0.7397
Epoch 60/100
804/804 [==============================] - 1s 873us/step - loss: 0.5397 - accuracy: 0.7384
Epoch 61/100
804/804 [==============================] - 1s 898us/step - loss: 0.5398 - accuracy: 0.7383
Epoch 62/100
804/804 [==============================] - 1s 876us/step - loss: 0.5396 - accuracy: 0.7386
Epoch 63/100
804/804 [==============================] - 1s 905us/step - loss: 0.5395 - accuracy: 0.7386
Epoch 64/100
804/804 [==============================] - 1s 865us/step - loss: 0.5393 - accuracy: 0.7385
Epoch 65/100
804/804 [==============================] - 1s 990us/step - loss: 0.5395 - accuracy: 0.7388
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5388 - accuracy: 0.7395
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7393
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7381
Epoch 69/100
804/804 [==============================] - 1s 942us/step - loss: 0.5395 - accuracy: 0.7381
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5389 - accuracy: 0.7385
Epoch 71/100
804/804 [==============================] - 1s 973us/step - loss: 0.5394 - accuracy: 0.7386
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7390
Epoch 73/100
804/804 [==============================] - 1s 960us/step - loss: 0.5392 - accuracy: 0.7395
Epoch 74/100
804/804 [==============================] - 1s 940us/step - loss: 0.5393 - accuracy: 0.7389
Epoch 75/100
804/804 [==============================] - 1s 989us/step - loss: 0.5389 - accuracy: 0.7392
Epoch 76/100
804/804 [==============================] - 1s 957us/step - loss: 0.5394 - accuracy: 0.7383
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7391
Epoch 78/100
804/804 [==============================] - 1s 941us/step - loss: 0.5393 - accuracy: 0.7395
Epoch 79/100
804/804 [==============================] - 1s 911us/step - loss: 0.5389 - accuracy: 0.7401
Epoch 80/100

804/804 [==============================] - 1s 890us/step - loss: 0.5389 - accuracy: 0.7388
Epoch 81/100
804/804 [==============================] - 1s 875us/step - loss: 0.5389 - accuracy: 0.7396
Epoch 82/100
804/804 [==============================] - 1s 930us/step - loss: 0.5391 - accuracy: 0.7390
Epoch 83/100
804/804 [==============================] - 1s 869us/step - loss: 0.5389 - accuracy: 0.7398
Epoch 84/100
804/804 [==============================] - 1s 852us/step - loss: 0.5389 - accuracy: 0.7390
Epoch 85/100
804/804 [==============================] - 1s 876us/step - loss: 0.5390 - accuracy: 0.7400
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5388 - accuracy: 0.7387
Epoch 87/100
804/804 [==============================] - 1s 873us/step - loss: 0.5389 - accuracy: 0.7407
Epoch 88/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7390
Epoch 89/100
804/804 [==============================] - 1s 865us/step - loss: 0.5390 - accuracy: 0.7401
Epoch 90/100
804/804 [==============================] - 1s 856us/step - loss: 0.5389 - accuracy: 0.7390
Epoch 91/100
804/804 [==============================] - 1s 867us/step - loss: 0.5388 - accuracy: 0.7393
Epoch 92/100
804/804 [==============================] - 1s 879us/step - loss: 0.5387 - accuracy: 0.7396
Epoch 93/100
804/804 [==============================] - 1s 863us/step - loss: 0.5388 - accuracy: 0.7393
Epoch 94/100
804/804 [==============================] - 1s 930us/step - loss: 0.5387 - accuracy: 0.7392
Epoch 95/100
804/804 [==============================] - 1s 868us/step - loss: 0.5384 - accuracy: 0.7390
Epoch 96/100
804/804 [==============================] - 1s 871us/step - loss: 0.5388 - accuracy: 0.7385
Epoch 97/100
804/804 [==============================] - 1s 862us/step - loss: 0.5383 - accuracy: 0.7393
Epoch 98/100
804/804 [==============================] - 1s 867us/step - loss: 0.5387 - accuracy: 0.7397
Epoch 99/100
804/804 [==============================] - 1s 891us/step - loss: 0.5385 - accuracy: 0.7393
Epoch 100/100
804/804 [==============================] - 1s 878us/step - loss: 0.5386 - accuracy: 0.7403
268/268 - 0s - loss: 0.5585 - accuracy: 0.7238 - 259ms/epoch - 966us/step
Loss: 0.5585026741027832, Accuracy: 0.7238484025001526

In [119]:
# Train the model - testing drop 2 more columns and run 150 epochs
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/100
804/804 [==============================] - 1s 901us/step - loss: 0.5383 - accuracy: 0.7386
Epoch 2/100
804/804 [==============================] - 1s 868us/step - loss: 0.5386 - accuracy: 0.7397
Epoch 3/100
804/804 [==============================] - 1s 869us/step - loss: 0.5385 - accuracy: 0.7387
Epoch 4/100
804/804 [==============================] - 1s 863us/step - loss: 0.5383 - accuracy: 0.7395
Epoch 5/100
804/804 [==============================] - 1s 885us/step - loss: 0.5383 - accuracy: 0.7389
Epoch 6/100
804/804 [==============================] - 1s 913us/step - loss: 0.5383 - accuracy: 0.7385
Epoch 7/100
804/804 [==============================] - 1s 946us/step - loss: 0.5384 - accuracy: 0.7393
Epoch 8/100
804/804 [==============================] - 1s 967us/step - loss: 0.5386 - accuracy: 0.7392
Epoch 9/100
804/804 [==============================] - 1s 956us/step - loss: 0.5383 - accuracy: 0.7400
Epoch 10/100
804/804 [==============================] - 1s 929us/step - loss: 0.5383 - accuracy: 0.7390
Epoch 11/100
804/804 [==============================] - 1s 956us/step - loss: 0.5385 - accuracy: 0.7395
Epoch 12/100
804/804 [==============================] - 1s 940us/step - loss: 0.5386 - accuracy: 0.7393
Epoch 13/100
804/804 [==============================] - 1s 943us/step - loss: 0.5381 - accuracy: 0.7396
Epoch 14/100
804/804 [==============================] - 1s 982us/step - loss: 0.5381 - accuracy: 0.7390
Epoch 15/100
804/804 [==============================] - 1s 955us/step - loss: 0.5380 - accuracy: 0.7392
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5381 - accuracy: 0.7387
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5383 - accuracy: 0.7394
Epoch 18/100
804/804 [==============================] - 1s 861us/step - loss: 0.5385 - accuracy: 0.7389
Epoch 19/100
804/804 [==============================] - 1s 886us/step - loss: 0.5379 - accuracy: 0.7385
Epoch 20/100
804/804 [==============================] - 1s 992us/step - loss: 0.5382 - accuracy: 0.7395
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5381 - accuracy: 0.7400
Epoch 22/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7407
Epoch 23/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5381 - accuracy: 0.7393
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5382 - accuracy: 0.7381
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7392
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5382 - accuracy: 0.7390
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5382 - accuracy: 0.7397
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5376 - accuracy: 0.7389
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7403
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7398
Epoch 31/100
804/804 [==============================] - 1s 979us/step - loss: 0.5380 - accuracy: 0.7392
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7395
Epoch 33/100
804/804 [==============================] - 1s 997us/step - loss: 0.5379 - accuracy: 0.7402
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5377 - accuracy: 0.7376
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7394
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7386
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7395
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5380 - accuracy: 0.7397
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5376 - accuracy: 0.7393
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5376 - accuracy: 0.7387
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5377 - accuracy: 0.7397
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5377 - accuracy: 0.7396
Epoch 43/100
804/804 [==============================] - 1s 981us/step - loss: 0.5378 - accuracy: 0.7390
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5377 - accuracy: 0.7404
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5377 - accuracy: 0.7396
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5376 - accuracy: 0.7392
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7390
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7397
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5376 - accuracy: 0.7379
Epoch 50/100
804/804 [==============================] - 1s 996us/step - loss: 0.5378 - accuracy: 0.7403
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7397
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7387
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7396
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7398
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5377 - accuracy: 0.7396
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5377 - accuracy: 0.7399
Epoch 57/100
804/804 [==============================] - 1s 998us/step - loss: 0.5374 - accuracy: 0.7400
Epoch 58/100
804/804 [==============================] - 1s 981us/step - loss: 0.5377 - accuracy: 0.7385
Epoch 59/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5376 - accuracy: 0.7388
Epoch 60/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5377 - accuracy: 0.7401
Epoch 61/100
804/804 [==============================] - 1s 977us/step - loss: 0.5374 - accuracy: 0.7390
Epoch 62/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5373 - accuracy: 0.7393
Epoch 63/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7403
Epoch 64/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5372 - accuracy: 0.7396
Epoch 65/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7389
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7389
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5373 - accuracy: 0.7387
Epoch 68/100
804/804 [==============================] - 1s 988us/step - loss: 0.5377 - accuracy: 0.7387
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7404
Epoch 70/100
804/804 [==============================] - 1s 990us/step - loss: 0.5373 - accuracy: 0.7393
Epoch 71/100
804/804 [==============================] - 1s 998us/step - loss: 0.5376 - accuracy: 0.7397
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7400
Epoch 73/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7403
Epoch 74/100
804/804 [==============================] - 1s 996us/step - loss: 0.5373 - accuracy: 0.7406
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7404
Epoch 76/100
804/804 [==============================] - 1s 991us/step - loss: 0.5373 - accuracy: 0.7400
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5372 - accuracy: 0.7397
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5371 - accuracy: 0.7397
Epoch 79/100
804/804 [==============================] - 1s 976us/step - loss: 0.5375 - accuracy: 0.7401
Epoch 80/100

804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7392
Epoch 81/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5372 - accuracy: 0.7409
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7390
Epoch 83/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7396
Epoch 84/100
804/804 [==============================] - 1s 968us/step - loss: 0.5373 - accuracy: 0.7403
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7397
Epoch 86/100
804/804 [==============================] - 1s 980us/step - loss: 0.5374 - accuracy: 0.7397
Epoch 87/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5368 - accuracy: 0.7400
Epoch 88/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5370 - accuracy: 0.7409
Epoch 89/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5371 - accuracy: 0.7392
Epoch 90/100
804/804 [==============================] - 1s 976us/step - loss: 0.5372 - accuracy: 0.7392
Epoch 91/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5371 - accuracy: 0.7401
Epoch 92/100
804/804 [==============================] - 1s 990us/step - loss: 0.5372 - accuracy: 0.7398
Epoch 93/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5371 - accuracy: 0.7408
Epoch 94/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5372 - accuracy: 0.7397
Epoch 95/100
804/804 [==============================] - 1s 990us/step - loss: 0.5370 - accuracy: 0.7400
Epoch 96/100
804/804 [==============================] - 1s 987us/step - loss: 0.5372 - accuracy: 0.7394
Epoch 97/100
804/804 [==============================] - 1s 984us/step - loss: 0.5371 - accuracy: 0.7394
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5371 - accuracy: 0.7398
Epoch 99/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5372 - accuracy: 0.7399
Epoch 100/100
804/804 [==============================] - 1s 991us/step - loss: 0.5373 - accuracy: 0.7395
268/268 - 0s - loss: 0.5585 - accuracy: 0.7263 - 327ms/epoch - 1ms/step
Loss: 0.5584846138954163, Accuracy: 0.7262973785400391

In [120]:
nn_model.save("AlphabetSoupCharity_Optimisation.keras")

In [121]:
nn_model.save("AlphabetSoupCharity_Optimisation.h5")

C:\Users\patricia.deassis\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(